name: Streamlit CI

on: #build 조건
  push:
    branches: [ "main" ]

env: #환경변수
  AWS_REGION: ap-northeast-2

jobs:
  build-and-test:
    runs-on: ubuntu-latest #실행 운영체제
    strategy:
      max-parallel: 4
      matrix: #언어 설정
        python-version: [3.11]
    steps: #실행 작업들
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --collect-only || true

  core-realese:
    needs: build-and-test 
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name lab-edu-cd-application-streamlit \
            --deployment-group-name lab-edu-cd-deploygroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}